### ISSUE TITLE
SIGSTKSZ is now a run-time variable

### ISSUE THREAD

**Issue by Empathy117** [NJU-ProjectN/fceux-am#2]
I got compiled failed

```shell
xxx/ics2021/abstract-machine/am/src/native/platform.h:23:11: error: variably modified ‘sigstack’ at file scope
   23 |   uint8_t sigstack[SIGSTKSZ];
      |           ^~~~~~~~
```

then I found this https://sourceware.org/pipermail/libc-alpha/2021-March/123553.html

I don't know do you will modify this for new glibc version, so I try to figure this out by myself.

I searched some older glibc header file and modify `uint8_t sigstack[SIGSTKSZ];` to `uint8_t sigstack[16384];` then I successfully compiled, but I always got some error, what ever number I used.
```shell
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x8800008
  Serial number of failed request:  8
  Current serial number in output stream:  9
```

I tired several numbers in this https://public-inbox.org/bug-gnulib/2419986.QI3XWb3JqY@omega/T/, but I think I'm doing it wrong, what should I do.

**Comment by sashimi-yzh** [comment]
For the `SIGSTKSZ` issue, we have already apply similar patch to the new branch. See [here](https://github.com/NJU-ProjectN/abstract-machine/commit/112799e02a28d22f03cfe496fe36408112047a71).

But for the `X Error`, maybe there is something wrong with your X server. It seems that such error is nothing to do with the code.

**Comment by Empathy117** [comment]
Thank you for your reply, yes I think I mix up two problems as same, finally I solve `X Error` using optimus manager switching my NVIDIA GPU to Intel GPU.
