### ISSUE TITLE
Segmentation fault (core dumped) in native.mk

### ISSUE THREAD

**Issue by Huanjia-Liu** [NJU-ProjectN/fceux-am#3]
Hello, I got the segmentation fault when running "make ARCH=native run mainargs=test" (mine ROM file is called test.nes).

After instruction, everything was going well, it can load the ROM file correctly, then a screen suddenly poped up and quickly closed. It shows me the error like the output I attached below.

> ############################################################################

+ LD -> build/fceux-native
/home/loserleo/git/ics2022/fceux-am/build/fceux-native
ROM is test
Starting FCEUX 2.2.3-interim git...
Found ROM 'test'
Loading ...

 PRG ROM:    2 x 16KiB
 CHR ROM:    1 x  8KiB
 ROM MD5:  0x8e3630186e35d477231bf8fd50e54cdd
 Mapper #:  0
 Mapper name: NROM
 Mirroring: Vertical
 Battery-backed: No
 Trained: No

Power on
Initializing video...
make: *** [/home/loserleo/git/ysyx-workbench/abstract-machine/scripts/native.mk:22: run] Segmentation fault (core dumped)
> ############################################################################

I checked line 22 in the file native.mk. 
`
run: image
	$(IMAGE)
`
Can't find any error. My Linux version is Ubuntu 20.04, my gcc version is 9.4.0. I'm a total freshman in C++, could u give me some tips or instructions to solve this problem? THANKS VERY MUCH.

**Comment by sashimi-yzh** [comment]
Many students have already run FCEUX on this plaftorm. Currently I have no idea about the error. Would you please try the following:
1. `make clean` and `make` again
2. try another ROM file

If it still procudes the same error, would you please provide your ROM file and let me test it?

**Comment by Huanjia-Liu** [comment]
Hello yzh, 
I tried three ROM files and finally found one works. My bad, should try a few more. Thanks a lot.

Just in case, here is the link to my ROM files: 
[ROM Links](https://drive.google.com/drive/folders/1sFuzPmb8CLeNmebgu1EXTwfkBYWV6Sb5?usp=sharing)
mario, mario1 can't work, and mario2 works well.





> Many students have already run FCEUX on this plaftorm. Currently I have no idea about the error. Would you please try the following:
> 
> 1. `make clean` and `make` again
> 2. try another ROM file
> 
> If it still procudes the same error, would you please provide your ROM file and let me test it?

**Comment by Huanjia-Liu** [comment]
Update,

The same problem happened after 10 hours lol. After various kinds of testing, I have to suspect that the problem is in my graphic driver. It works now after I purged all my NV graphic drivers and Cuda. 
Didn't test if it was caused by the version or something else, just leave a msg here if some get the same problem.

The version of my graphic driver and Cuda is 495.46 and 11.5. Also all three ROM files I attached above can work perfectly.

**Comment by YaQia** [comment]
I'm getting errors similarly but I think it is not that critical. I can only open those *.nes files in very low possibility. Otherwise I will get 2 different errors separately, the first one is totally identical with the issue, the other one is reported from my X server (Nvidia graphic card with proprietary driver).

Here is the second error's information: 
```bash
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  25 (X_SendEvent)
  Resource id in failed request:  0x2c00002
  Serial number of failed request:  8
  Current serial number in output stream:  9
```

BTW, I am using Manjaro, Gnome43.
