### ISSUE TITLE
[solved] LD -> build/fceux-native error

### ISSUE THREAD

**Issue by siliconrecycle** [NJU-ProjectN/fceux-am#4]
OS：fedora36
editor：emacs

If you don't use vim, and not develop in ubuntu, like me. When you make with 'make ARCH=native run mainargs=k', you maybe meet this question.
```
[qian@localhost fceux-am]$ make ARCH=native run mainargs=k
# Building fceux-run [native]
# Building am-archive [native]
# Building klib-archive [native]
# Creating image [native]
+ LD -> build/fceux-native
/usr/bin/ld: /home/qian/prj/ics2022/fceux-am/build/native/src/emufile.o:(.data.rel+0x8): undefined reference to `rom_mario_nes'
/usr/bin/ld: /home/qian/prj/ics2022/fceux-am/build/native/src/emufile.o:(.data.rel+0x10): undefined reference to `rom_mario_nes_len'
collect2: error: ld returned 1 exit status
make: *** [/home/qian/prj/ics2022/abstract-machine/scripts/native.mk:19: image] Error 1
```
This happens because `./fceux-am/nes/gen/mario.c` is empty. Look through the file `./fceux-am/nes/build-rom.py`, you will find `mario.c` is converted by mario.nes with `xdd` program. If you develop in fedora, you just need `sudo dnf in vim-common`. `xdd` is included in this package.

**Comment by SherlockShemol** [comment]
it's xxd not xdd.it's a tool to make (or reverse) a hex dump.
Archlinux meets the same problem when trying to play mario, and yay -S xxd can solve.
