### ISSUE TITLE
No member named 'gregs' and 'REG_RAX' in native.h

### ISSUE THREAD

**Issue by alexanderWangzz** [NJU-ProjectN/fceux-am#6]
I got complied failed ,In file included from /home/tzwangmx/ics2023/abstract-machine/am/include/am.h:7,
                 from /home/tzwangmx/ics2023/am-kernels/tests/am-tests/include/amtest.h:4,
                 from /home/tzwangmx/ics2023/am-kernels/tests/am-tests/src/tests/vm.c:1:
/home/tzwangmx/ics2023/am-kernels/tests/am-tests/src/tests/vm.c: In function ‘vm_handler’:
/home/tzwangmx/ics2023/abstract-machine/am/include/arch/native.h:22:29: error: ‘mcontext_t’ has no member named ‘gregs’; did you mean ‘regs’?
   22 | #define GPRx uc.uc_mcontext.gregs[REG_RAX]
      |                             ^~~~~
/home/tzwangmx/ics2023/am-kernels/tests/am-tests/src/tests/vm.c:37:26: note: in expansion of macro ‘GPRx’
   37 |       printf("%d ", ctx->GPRx);
      |                          ^~~~
/home/tzwangmx/ics2023/abstract-machine/am/include/arch/native.h:22:35: error: ‘REG_RAX’ undeclared (first use in this function)
   22 | #define GPRx uc.uc_mcontext.gregs[REG_RAX]
      |                                   ^~~~~~~
/home/tzwangmx/ics2023/am-kernels/tests/am-tests/src/tests/vm.c:37:26: note: in expansion of macro ‘GPRx’
   37 |       printf("%d ", ctx->GPRx);
      |                          ^~~~
/home/tzwangmx/ics2023/abstract-machine/am/include/arch/native.h:22:35: note: each undeclared identifier is reported only once for each function it appears in
   22 | #define GPRx uc.uc_mcontext.gregs[REG_RAX]
      |                                   ^~~~~~~
/home/tzwangmx/ics2023/am-kernels/tests/am-tests/src/tests/vm.c:37:26: note: in expansion of macro ‘GPRx’
   37 |       printf("%d ", ctx->GPRx);
      |                          ^~~~
make: *** [/home/tzwangmx/ics2023/abstract-machine/Makefile:110: /home/tzwangmx/ics2023/am-kernels/tests/am-tests/build/native/src/tests/vm.o] Error 1 
what should I do ?

**Comment by sashimi-yzh** [comment]
Do you use macOS with ARM architecture? If it is the case, we do not support ARM now.

**Comment by alexanderWangzz** [comment]
> Do you use macOS with ARM architecture? If it is the case, we do not support ARM now.

Yes. Does this mean I can't do the next few PAs?

**Comment by sashimi-yzh** [comment]
Maybe you can finish everything without native. But we do not test on ARM yet.

**Comment by alexanderWangzz** [comment]
> Maybe you can finish everything without native. But we do not test on ARM yet
thx

**Comment by alexanderWangzz** [comment]
> Maybe you can finish everything without native. But we do not test on ARM yet.

thx
