### ISSUE TITLE
有关存档的内容

### ISSUE THREAD

**Issue by ccnuktd** [NJU-ProjectN/fceux-am#7]
由于目前还没有看模拟机的源码，只是尝试了玩游戏。我有些好奇如果要在这个基础上实现游戏存档，要去了解一些什么。可以给一些思路吗？

**Comment by sashimi-yzh** [comment]
存档功能在移植的时候已经去掉了, 所以无法实现存档. 如果你想了解存档如何实现, 可以参考FCEUX的上游代码.

**Comment by ccnuktd** [comment]
> 存档功能在移植的时候已经去掉了, 所以无法实现存档. 如果你想了解存档如何实现, 可以参考FCEUX的上游代码.

感谢！突然意识到我发现我在nvboard发的issue你也回答了，感谢大佬。
