### ISSUE TITLE
make ARCH=native mainargs=mario run    no video output

### ISSUE THREAD

**Issue by NeverHaving** [NJU-ProjectN/fceux-am#8]
ics-pa branch : 2023
ubuntu 22.04 desktop, not virtual mechine 
gcc version: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

i can run this command makemake ARCH=native run mainargs=mario ARCH=native mainargs=k run show like this:
![image](https://github.com/user-attachments/assets/e995cd92-a4cd-4c9c-ad97-66cd71b033da)
the keyboard respond is normal.

and then i download the roms from [roms](https://box.nju.edu.cn/f/3e56938d9d8140a7bb75/?dl=1),put mario.nes into rom folder.
run the command make ARCH=native run mainargs=mario, no video and sound, the terimial always output 0000 like this:
![image](https://github.com/user-attachments/assets/1b8bd79c-b5ca-4bea-926e-4321ba2c7abf)
only ctrl + c can interrupt the output

**Comment by sashimi-yzh** [comment]
This is strange. Would you please try to find which line of code outputs 0000?

**Comment by NeverHaving** [comment]
If I can debug this issue later? I try to add gdb enable with it,it seems a little problem with change the Makefile,maybe i should learn morn about gcc compile options about this.And i also try to use apt install fceux to run the mario,all things test good,so i guess my environment maybe is okey.

**Comment by sashimi-yzh** [comment]
Sure. You can discuss here if you have new progress.

**Comment by NeverHaving** [comment]
Update my progress,
i add some debug message in code 
![image](https://github.com/user-attachments/assets/d1329ccc-1609-4874-b72f-dde90db022ea)
![image](https://github.com/user-attachments/assets/f9176ac2-467a-472f-84a9-520bcf17ac63)
![image](https://github.com/user-attachments/assets/354df66d-dbb2-4d29-86a1-a3a64da7f4b3)
 use the make ARCH=native run mainargs=mario > mario.txt ,
through the mario.txt, find the debug message was print in CASE('m', mp_print, MPE);

**Comment by sashimi-yzh** [comment]
I think you are trying to run fceux under a wrong directory.

**Comment by NeverHaving** [comment]
i think i find the problem, it is my mistake. I make the fceux in a wrong path. ::(
